// app/layout.tsx

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/*<nav className="bg-gray-800 text-white p-4">*/}
        {/*  <ul className="flex space-x-6">*/}
        {/*    <li><Link href="/">Главная</Link></li>*/}
        {/*    <li><Link href="/auth/login">Вход</Link></li>*/}
        {/*    <li><Link href="/auth/register">Регистрация</Link></li>*/}
        {/*  </ul>*/}
        {/*</nav>*/}


        {children}
      </body>
    </html>
  );
}